"""baseline_initial_schema

Revision ID: 9a07ccdca3aa
Revises:
Create Date: 2026-03-18 09:48:33.574417

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a07ccdca3aa'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumos_cuota_id'), table_name='consumos_cuota')
    op.drop_table('consumos_cuota')
    op.drop_index(op.f('ix_centros_costo_id'), table_name='centros_costo')
    op.drop_table('centros_costo')
    op.drop_index(op.f('ix_presupuesto_mensual_id'), table_name='presupuesto_mensual')
    op.drop_table('presupuesto_mensual')
    op.drop_index(op.f('ix_tarjetas_credito_id'), table_name='tarjetas_credito')
    op.drop_table('tarjetas_credito')
    op.drop_index(op.f('ix_cuentas_bancarias_id'), table_name='cuentas_bancarias')
    op.drop_table('cuentas_bancarias')
    op.drop_index(op.f('ix_servicios_fijos_id'), table_name='servicios_fijos')
    op.drop_index(op.f('uq_servicio_fijo_desc'), table_name='servicios_fijos')
    op.drop_table('servicios_fijos')
    op.drop_index(op.f('ix_transacciones_dss_id'), table_name='transacciones_dss')
    op.drop_index(op.f('uq_transaccion_dss_dup'), table_name='transacciones_dss')
    op.drop_table('transacciones_dss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacciones_dss',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('cuenta_id', sa.INTEGER(), nullable=True),
    sa.Column('centro_costo_id', sa.INTEGER(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=300), nullable=False),
    sa.Column('monto', sa.FLOAT(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=80), nullable=True),
    sa.Column('moneda', sa.VARCHAR(length=5), nullable=True),
    sa.Column('es_recurrente', sa.BOOLEAN(), nullable=True),
    sa.Column('notas', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_bancarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('uq_transaccion_dss_dup'), 'transacciones_dss', ['cliente_id', 'fecha', 'descripcion', 'monto'], unique=1)
    op.create_index(op.f('ix_transacciones_dss_id'), 'transacciones_dss', ['id'], unique=False)
    op.create_table('servicios_fijos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('monto_ars', sa.FLOAT(), nullable=False),
    sa.Column('dia_debito', sa.INTEGER(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=80), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('uq_servicio_fijo_desc'), 'servicios_fijos', ['cliente_id', 'descripcion'], unique=1)
    op.create_index(op.f('ix_servicios_fijos_id'), 'servicios_fijos', ['id'], unique=False)
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('banco', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=30), nullable=True),
    sa.Column('saldo_inicial', sa.FLOAT(), nullable=True),
    sa.Column('moneda', sa.VARCHAR(length=5), nullable=True),
    sa.Column('activa', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_bancarias_id'), 'cuentas_bancarias', ['id'], unique=False)
    op.create_table('tarjetas_credito',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('banco', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('limite_ars', sa.FLOAT(), nullable=True),
    sa.Column('tna_financiacion', sa.FLOAT(), nullable=True),
    sa.Column('fecha_cierre_dia', sa.INTEGER(), nullable=True),
    sa.Column('fecha_vencimiento_dia', sa.INTEGER(), nullable=True),
    sa.Column('activa', sa.BOOLEAN(), nullable=True),
    sa.Column('regla_cierre', sa.TEXT(), server_default=sa.text("'FIJO'"), nullable=True),
    sa.Column('dias_hasta_vencimiento', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarjetas_credito_id'), 'tarjetas_credito', ['id'], unique=False)
    op.create_table('presupuesto_mensual',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('anio', sa.INTEGER(), nullable=False),
    sa.Column('mes', sa.INTEGER(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=False),
    sa.Column('monto_presupuestado', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_mensual_id'), 'presupuesto_mensual', ['id'], unique=False)
    op.create_table('centros_costo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_costo_id'), 'centros_costo', ['id'], unique=False)
    op.create_table('consumos_cuota',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tarjeta_id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=300), nullable=False),
    sa.Column('monto_total_ars', sa.FLOAT(), nullable=False),
    sa.Column('cuotas_total', sa.INTEGER(), nullable=True),
    sa.Column('cuotas_pagadas', sa.INTEGER(), nullable=True),
    sa.Column('cuota_mensual', sa.FLOAT(), nullable=True),
    sa.Column('tasa_cuota', sa.FLOAT(), nullable=True),
    sa.Column('fecha_primera_cuota', sa.DATE(), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjetas_credito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumos_cuota_id'), 'consumos_cuota', ['id'], unique=False)
    # ### end Alembic commands ###
